### ISSUE TITLE
InvalidOperationException Arkangelsk and Narvik Insertion

### ISSUE THREAD

**Issue by FirebarSim** [DotModGroup/ColdWaters-DotMod#146] opened 2023-03-07 19:27 UTC
![image](https://user-images.githubusercontent.com/32907623/223531045-8cefade5-5e00-4a1b-ad9a-e1be2f2ccd21.png)

**Comment by HobbitJack** [comment] 2023-05-30 02:18
Duplicate of #118, leaving for clerical purposes.

**Comment by HobbitJack** [comment] 2023-12-19 02:07
Issue has been solved in dev.

**Closed by HobbitJack** 2023-12-19 02:07 UTC
Labels: bug, duplicate
