### ISSUE TITLE
Error:failed to play voicemanager.xxx

### ISSUE THREAD

**Issue by Thyast** [DotModGroup/ColdWaters-DotMod#135] opened 2022-10-18 20:58 UTC
![image](https://user-images.githubusercontent.com/65755771/196543379-f428835e-20e6-4988-a2ba-c8790ff5646a.png)

**Comment by HobbitJack** [comment] 2022-12-28 19:12
This is a known issue which we will attempt to look into for future releases of the mod.

**Comment by HobbitJack** [comment] 2023-05-30 02:19
Also a duplicate of #86.

**Closed by HobbitJack** 2023-05-30 02:19 UTC
Labels: bug, duplicate
