### ISSUE TITLE
Playable Helicopters from surface ships have no torpedoes?

### ISSUE THREAD

**Issue by hammer2019** [DotModGroup/ColdWaters-DotMod#143] opened 2023-01-01 16:43 UTC
even with land on mother ship no change !
what's the matter? 

also i have a few missile change in Ticonderoga  is that related ?  if is whats is solution !??

**Comment by HobbitJack** [comment] 2023-01-01 22:41
Please include a screenshot of your game with the problem.

**Comment by HobbitJack** [comment] 2023-12-19 02:08
Issue closed as likely caused by improperly set up vessel files.

**Closed by HobbitJack** 2023-12-19 02:08 UTC
Labels: error, needs info
