### ISSUE TITLE
Error due running game after install

### ISSUE THREAD

**Issue by hammer2019** [DotModGroup/ColdWaters-DotMod#92] opened 2022-05-06 08:27 UTC
I got this error after running game with the Dot mod

File Validation Failed due to non-vanilla file at path: \globalgamemanagers.The application will exit now

![Dotmod Error](https://user-images.githubusercontent.com/41520033/167095762-8e233593-b7b4-4bf3-8cd9-9838210738a8.jpg)

**Comment by HobbitJack** [comment] 2022-05-06 10:01
This almost invariably means you have unsuccessfully uninstalled EpicMod or any other mod which changes resources.assets. Manually remove your game directory through File Explorer and then re-install through Steam/GoG.

**Comment by SpitefulGit** [comment] 2022-05-07 11:32
@HobbitJack I'm having the same issue, although as far as I'm aware I correctly uninstalled EpicMod using it's uninstall feature in the menu

**Comment by HobbitJack** [comment] 2022-05-07 13:07
Closing because this is a local issue caused by an improper installation.

**Closed by HobbitJack** 2022-05-07 13:07 UTC

**Comment by hammer2019** [comment] 2022-05-07 14:24
> This almost invariably means you have unsuccessfully uninstalled EpicMod or any other mod which changes resources.assets. Manually remove your game directory through File Explorer and then re-install through Steam/GoG.

Downloading GOG version And Reinstalling mode also Excluding antivirus software for installer of mode worked perfectly !
